name: dolphin_flutter
description: Dolphin Shared Library
version: 0.0.74
homepage: https://www.neture.com.br

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.0
  uuid: ^4.1.0

  # Text
  quiver: ^3.2.1
  cpf_cnpj_validator: ^2.0.0
  units_converter: ^2.1.1
  timeago: ^3.5.0
  email_validator: ^2.1.17

  # Language and Region
  intl: ^0.18.1

  # Logging
  logger: ^2.0.2+1

  # Tag Editor
  pointer_interceptor: ^0.9.3+6
  debounce_throttle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
