name: dolphin_flutter
description: Dolphin Shared Library
version: 0.0.13
homepage: https://www.neture.com.br

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  package_info_plus: ^1.3.0

  # Text
  quiver: ^3.0.1
  recase: ^4.0.0
  cpf_cnpj_validator: ^2.0.0

  # Language and Region
  intl: ^0.17.0

  # Fonts
  google_fonts: ^2.2.0

  # Logging
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
