name: dolphin_flutter
description: Dolphin Shared Library
version: 0.0.61
homepage: https://www.neture.com.br

environment:
  sdk: ">=2.18.4 <3.3.8"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  package_info_plus: ^3.0.3
  device_info_plus: ^8.1.0
  uuid: ^3.0.7

  # Text
  quiver: ^3.2.1
  cpf_cnpj_validator: ^2.0.0
  units_converter: ^2.1.0
  timeago: ^3.4.0
  email_validator: ^2.1.17

  # Language and Region
  intl: ^0.18.0

  # Logging
  logger: ^1.3.0

  # Tag Editor
  pointer_interceptor: ^0.9.3+4
  debounce_throttle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
