name: dolphin_flutter
description: Dolphin Shared Library
version: 0.0.48
homepage: https://www.neture.com.br

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  package_info_plus: ^1.3.0

  # Text
  quiver: ^3.1.0
  cpf_cnpj_validator: ^2.0.0
  units_converter: ^2.0.1
  timeago: ^3.3.0
  email_validator: ^2.1.17

  # Language and Region
  intl: ^0.17.0

  # Logging
  logger: ^1.1.0

  # Tag Editor
  pointer_interceptor: ^0.9.3+3
  debounce_throttle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
