name: dolphin_flutter
description: Dolphin Shared Library
version: 0.0.3
author:
homepage: https://www.neture.com.br

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  package_info: ^2.0.0

  # Text
  quiver: ^2.0.5
  recase: ^4.0.0
  cpf_cnpj_validator: ^2.0.0

  # Language and Region
  intl: ^0.17.0

  # Fonts
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
